### ISSUE TITLE
Image gallery saver not saving image to my gallery(Android) after flutter SDK and gardle update.

### ISSUE THREAD

**Issue by token-lyd** [hui-z/image_gallery_saver#102]
I update my flutter SDK yesterday, update Gradle, and did flutter create .  + flutter clean command.  

But after this, the image screenshot is not saving to my android gallery on my phone. It was working fine before.

I this what in my run command.....

`I/flutter ( 1484): PermissionStatus.granted
I/mali_egl( 1484): eglDestroySurface() in
I/mali_winsys( 1484): delete_surface() [521x114] return
I/mali_egl( 1484): eglDestroySurface() out
W/libEGL  ( 1484): EGLNativeWindowType 0x7cb82d28d0 disconnect failed
D/ViewRootImpl@c1e5e9[Toast]( 1484): dispatchDetachedFromWindow
D/InputTransport( 1484): Input channel destroyed: 'e2ff0f3', fd=96
D/ViewRootImpl@49458f7[MainActivity]( 1484): ViewPostIme pointer 0
D/ViewRootImpl@49458f7[MainActivity]( 1484): ViewPostIme pointer 1
W/System.err( 1484): java.io.FileNotFoundException: /storage/emulated/0/medSOS/1596259427774.jpg: open failed: EACCES (Permission denied)
W/System.err( 1484): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err( 1484): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
W/System.err( 1484): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
W/System.err( 1484): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.saveImageToGallery(ImageGallerySaverPlugin.kt:64)
W/System.err( 1484): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.onMethodCall(ImageGallerySaverPlugin.kt:36)
W/System.err( 1484): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
W/System.err( 1484): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err( 1484): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
W/System.err( 1484): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 1484): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err( 1484): 	at android.os.Looper.loop(Looper.java:197)
W/System.err( 1484): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
W/System.err( 1484): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 1484): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err( 1484): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
W/System.err( 1484): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err( 1484): 	at libcore.io.Linux.open(Native Method)
W/System.err( 1484): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err( 1484): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err( 1484): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err( 1484): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7691)
W/System.err( 1484): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err( 1484): 	... 14 more
I/flutter ( 1484): 
D/ViewRootImpl@315eb2b[Toast]( 1484): setView = android.widget.FrameLayout@c3e6b88 TM=true MM=false
D/ViewRootImpl@315eb2b[Toast]( 1484): Relayout returned: old=(0,83,1080,2214) new=(279,2000,800,2114) req=(521,114)0 dur=8 res=0x7 s={true 538003476480} ch=true
D/OpenGLRenderer( 1484): createReliableSurface : 0x7cb82d28c0, 0x7d43819000
I/mali_winsys( 1484): new_window_surface() [521x114] return: 0x3000
D/ViewRootImpl@315eb2b[Toast]( 1484): MSG_RESIZED: frame=(279,2000,800,2114) ci=(0,0,0,0) vi=(0,0,521,114) or=1
I/mali_egl( 1484): eglDestroySurface() in
I/mali_winsys( 1484): delete_surface() [521x114] return
I/mali_egl( 1484): eglDestroySurface() out
W/libEGL  ( 1484): EGLNativeWindowType 0x7cb82d28d0 disconnect failed
D/ViewRootImpl@315eb2b[Toast]( 1484): dispatchDetachedFromWindow
D/InputTransport( 1484): Input channel destroyed: 'e24d1f8', fd=95
D/InputMethodManager( 1484): prepareNavigationBarInfo() DecorView@c956d15[MainActivity]
D/InputMethodManager( 1484): getNavigationBarColor() -855310
V/InputMethodManager( 1484): Starting input: tba=medrunner.sos_id_app ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 1484): startInputInner - Id : 0
I/InputMethodManager( 1484): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 1484): Input channel destroyed: 'ClientS', fd=93
D/ViewRootImpl@49458f7[MainActivity]( 1484): stopped(true) old=false
D/SurfaceView( 1484): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{42b8d93 V.E...... ........ 0,0-1080,2214} of ViewRootImpl@49458f7[MainActivity]
D/SurfaceView( 1484): surfaceDestroyed callback.size 1 #1 io.flutter.embedding.android.FlutterSurfaceView{42b8d93 V.E...... ........ 0,0-1080,2214}
I/mali_egl( 1484): eglDestroySurface() in
I/mali_winsys( 1484): delete_surface() [1080x2214] return
I/mali_egl( 1484): eglDestroySurface() out
W/libEGL  ( 1484): EGLNativeWindowType 0x7d3e8ac010 disconnect failed
D/SurfaceView( 1484): remove() io.flutter.embedding.android.FlutterSurfaceView{42b8d93 V.E...... ........ 0,0-1080,2214} Surface(name=SurfaceView - medrunner.sos_id_app/medrunner.sos_id_app.MainActivity@42b8d93@3)/@0x2360146
D/ViewRootImpl@49458f7[MainActivity]( 1484): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 1484): prepareNavigationBarInfo() DecorView@c956d15[MainActivity]
D/InputMethodManager( 1484): getNavigationBarColor() -855310
E/ViewRootImpl@49458f7[MainActivity]( 1484): Surface is not valid.
`

**Comment by token-lyd** [comment]
I/flutter ( 1484): PermissionStatus.granted
I/mali_egl( 1484): eglDestroySurface() in
I/mali_winsys( 1484): delete_surface() [521x114] return
I/mali_egl( 1484): eglDestroySurface() out
W/libEGL  ( 1484): EGLNativeWindowType 0x7cb82d28d0 disconnect failed
D/ViewRootImpl@c1e5e9[Toast]( 1484): dispatchDetachedFromWindow
D/InputTransport( 1484): Input channel destroyed: 'e2ff0f3', fd=96
D/ViewRootImpl@49458f7[MainActivity]( 1484): ViewPostIme pointer 0
D/ViewRootImpl@49458f7[MainActivity]( 1484): ViewPostIme pointer 1
W/System.err( 1484): java.io.FileNotFoundException: /storage/emulated/0/medSOS/1596259427774.jpg: open failed: EACCES (Permission denied)
W/System.err( 1484): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err( 1484): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
W/System.err( 1484): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
W/System.err( 1484): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.saveImageToGallery(ImageGallerySaverPlugin.kt:64)
W/System.err( 1484): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.onMethodCall(ImageGallerySaverPlugin.kt:36)
W/System.err( 1484): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
W/System.err( 1484): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err( 1484): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
W/System.err( 1484): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 1484): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err( 1484): 	at android.os.Looper.loop(Looper.java:197)
W/System.err( 1484): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
W/System.err( 1484): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 1484): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err( 1484): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
W/System.err( 1484): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err( 1484): 	at libcore.io.Linux.open(Native Method)
W/System.err( 1484): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err( 1484): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err( 1484): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err( 1484): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7691)
W/System.err( 1484): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err( 1484): 	... 14 more
I/flutter ( 1484): 
D/ViewRootImpl@315eb2b[Toast]( 1484): setView = android.widget.FrameLayout@c3e6b88 TM=true MM=false
D/ViewRootImpl@315eb2b[Toast]( 1484): Relayout returned: old=(0,83,1080,2214) new=(279,2000,800,2114) req=(521,114)0 dur=8 res=0x7 s={true 538003476480} ch=true
D/OpenGLRenderer( 1484): createReliableSurface : 0x7cb82d28c0, 0x7d43819000
I/mali_winsys( 1484): new_window_surface() [521x114] return: 0x3000
D/ViewRootImpl@315eb2b[Toast]( 1484): MSG_RESIZED: frame=(279,2000,800,2114) ci=(0,0,0,0) vi=(0,0,521,114) or=1
I/mali_egl( 1484): eglDestroySurface() in
I/mali_winsys( 1484): delete_surface() [521x114] return
I/mali_egl( 1484): eglDestroySurface() out
W/libEGL  ( 1484): EGLNativeWindowType 0x7cb82d28d0 disconnect failed
D/ViewRootImpl@315eb2b[Toast]( 1484): dispatchDetachedFromWindow
D/InputTransport( 1484): Input channel destroyed: 'e24d1f8', fd=95
D/InputMethodManager( 1484): prepareNavigationBarInfo() DecorView@c956d15[MainActivity]
D/InputMethodManager( 1484): getNavigationBarColor() -855310
V/InputMethodManager( 1484): Starting input: tba=medrunner.sos_id_app ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 1484): startInputInner - Id : 0
I/InputMethodManager( 1484): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 1484): Input channel destroyed: 'ClientS', fd=93
D/ViewRootImpl@49458f7[MainActivity]( 1484): stopped(true) old=false
D/SurfaceView( 1484): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{42b8d93 V.E...... ........ 0,0-1080,2214} of ViewRootImpl@49458f7[MainActivity]
D/SurfaceView( 1484): surfaceDestroyed callback.size 1 #1 io.flutter.embedding.android.FlutterSurfaceView{42b8d93 V.E...... ........ 0,0-1080,2214}
I/mali_egl( 1484): eglDestroySurface() in
I/mali_winsys( 1484): delete_surface() [1080x2214] return
I/mali_egl( 1484): eglDestroySurface() out
W/libEGL  ( 1484): EGLNativeWindowType 0x7d3e8ac010 disconnect failed
D/SurfaceView( 1484): remove() io.flutter.embedding.android.FlutterSurfaceView{42b8d93 V.E...... ........ 0,0-1080,2214} Surface(name=SurfaceView - medrunner.sos_id_app/medrunner.sos_id_app.MainActivity@42b8d93@3)/@0x2360146
D/ViewRootImpl@49458f7[MainActivity]( 1484): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 1484): prepareNavigationBarInfo() DecorView@c956d15[MainActivity]
D/InputMethodManager( 1484): getNavigationBarColor() -855310
E/ViewRootImpl@49458f7[MainActivity]( 1484): Surface is not valid.

**Comment by token-lyd** [comment]
Please note: My MainActivity.kt file was missing, so I did a flutter create command to restore it.
