### ISSUE TITLE
Crash at new master version[Android]

### ISSUE THREAD

**Issue by qiaoshouqing** [hui-z/image_gallery_saver#110]
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Mac OS X 10.15.6 19G2021
    x86_64, locale zh-Hans)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2018.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.49.0)
[✓] Proxy Configuration
[✓] Connected device (6 available)
```

```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
        at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:119)
        at com.example.imagegallerysaver.ImageGallerySaverPlugin$Companion.registerWith(ImageGallerySaverPlugin.kt:25)
        at com.example.imagegallerysaver.ImageGallerySaverPlugin.registerWith(ImageGallerySaverPlugin.kt)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)
        at top.glimpse.tomatoplan.MainActivity.configureFlutterEngine(MainActivity.java:40)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:181)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
        at android.app.Activity.performCreate(Activity.java:6279)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2396)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2503) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
```

**Comment by jiangzhiguo1992** [comment]
same with you

**Comment by myAndyour** [comment]
我也遇到了同样的问题，调用了2次GeneratedPluginRegistrant.registerWith(flutterEngine)导致的，去掉一个就好了
