### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by jhj0517** [hui-z/image_gallery_saver#282]
Tested on Android13

added 
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
on Manifest but this still happens

```
I/System.out(27113): ImageGallerySaverPlugin 80
E/DartMessenger(27113): Uncaught exception in binary message listener
E/DartMessenger(27113): java.io.FileNotFoundException: content:/media/external/images/media/1000000881: open failed: ENOENT (No such file or directory)
E/DartMessenger(27113): 	at libcore.io.IoBridge.open(IoBridge.java:574)
E/DartMessenger(27113): 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
E/DartMessenger(27113): 	at java.io.FileInputStream.<init>(FileInputStream.java:115)
E/DartMessenger(27113): 	at androidx.exifinterface.media.ExifInterface.initForFilename(ExifInterface.java:5288)
E/DartMessenger(27113): 	at androidx.exifinterface.media.ExifInterface.<init>(ExifInterface.java:3955)
E/DartMessenger(27113): 	at com.cloudacy.native_exif.NativeExifPlugin.onMethodCall(NativeExifPlugin.kt:61)
E/DartMessenger(27113): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/DartMessenger(27113): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/DartMessenger(27113): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/DartMessenger(27113): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(27113): 	at android.os.Handler.handleCallback(Handler.java:942)
E/DartMessenger(27113): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(27113): 	at android.os.Looper.loopOnce(Looper.java:226)
E/DartMessenger(27113): 	at android.os.Looper.loop(Looper.java:313)
E/DartMessenger(27113): 	at android.app.ActivityThread.main(ActivityThread.java:8762)
E/DartMessenger(27113): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(27113): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/DartMessenger(27113): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/DartMessenger(27113): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
E/DartMessenger(27113): 	at libcore.io.Linux.open(Native Method)
E/DartMessenger(27113): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
E/DartMessenger(27113): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
E/DartMessenger(27113): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
E/DartMessenger(27113): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8624)
E/DartMessenger(27113): 	at libcore.io.IoBridge.open(IoBridge.java:560)
E/DartMessenger(27113): 	... 17 more
I/flutter (27113): saveImageWithExif error : MissingPluginException(No implementation found for method initPath on channel native_exif)

```

**Comment by jhj0517** [comment]
sorr
