### ISSUE TITLE
No such file or directory errror, even though has storage permission

### ISSUE THREAD

**Issue by clearloop** [hui-z/image_gallery_saver#57]
### `logs`

```
W/System.err(10093): java.io.FileNotFoundException: /storage/emulated/0/xxx/1571468048334.png: open failed: ENOENT (No such file or directory)
W/System.err(10093):    at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(10093):    at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
W/System.err(10093):    at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
W/System.err(10093):    at com.example.imagegallerysaver.ImageGallerySaverPlugin.saveImageToGallery(ImageGallerySaverPlugin.kt:61)
W/System.err(10093):    at com.example.imagegallerysaver.ImageGallerySaverPlugin.onMethodCall(ImageGallerySaverPlugin.kt:33)
W/System.err(10093):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
W/System.err(10093):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
W/System.err(10093):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:645)
W/System.err(10093):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(10093):    at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err(10093):    at android.os.Looper.loop(Looper.java:174)
W/System.err(10093):    at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(10093):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(10093):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err(10093):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
W/System.err(10093): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err(10093):    at libcore.io.Linux.open(Native Method)
W/System.err(10093):    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(10093):    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(10093):    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(10093):    at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
W/System.err(10093):    at libcore.io.IoBridge.open(IoBridge.java:482)
```

+ Already reinstalled the app
+ iOS performs well

## AndroidManifest
```
...
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
...
```

**Comment by ZNBmm** [comment]
me too

**Comment by ZNBmm** [comment]
you need to ask for storage permission to save the image. I using https://github.com/BaseflowIT/flutter-permission-handler to handle permission for me.

**Comment by clearloop** [comment]
Clean builds and restart all programs.
